export type Bordero = {
    id_bordero: number,
    descricao: string,
    cod_conta_caixa: number,
    nome_banco: string,
    numero_banco: string,
    data_criacao: string,
    numero_agencia_banco: string,    
    numero_conta_banco: string,
    statusaprovacaobordero: string,
    cod_convenio_banco: string,
    aprovadores: BorderoAprovacao[],
}
export type BorderoItem = {
    id: number,
    id_bordero: number,
    data_criacao: string,
    validade_bordero: string,
	id_lancamento_fin: number,
	numero_nota_financeiro: string,
	id_movimento_ligacao: number,
	descricao_historico_lan: string,
	data_criacao_lan: string,
	data_vencimento_lan: string,
	valor_bruto_lan: number,
	desc_vl_irrf: number,
    desc_vl_iss: number,
    desc_vl_taxas: number,
    desc_vl_inss: number,
    desc_vl_multa: number,
    cod_fornecedor: string,
    tipo_documento_lan: string,
    conta_de_centrocusto: string,
    nat_financeira: string,
    possui_anexo: boolean,
}
export type BorderoAprovacao = {
    id?: number,
    data_aprovacao?: string,
    aprovacao?: string,
    usuario: string,
    nome?: string,
    ativo: number,
}